### ISSUE TITLE
nats-spring-boot-starter in not up to date

### ISSUE THREAD

**Issue by moleksyuk** [nats-io/spring-nats#14]
Hi,

`io.nats:nats-spring-boot-starter:0.4.0` depends on `io.nats:jnats:2.5.2`

`io.nats:jnats2.5.2`- doesn't have randomize servers if you specify multiple servers (cluster setup). So each NatsConnection will be established to the first server and leads load only to one node in nast cluster setup.

Any plans to update `nats-spring-boot-starter` to the latest version of `io.nats:jnats`?

**Comment by YunaBraska** [comment]
I think this is outdated, `jnats` is currently on `1.17.1` in this repo
