### ISSUE TITLE
Projekt Status?

### ISSUE THREAD

**Issue by ScienceOfficer** [nats-io/spring-nats#17]
@sasbury Hello! Could you tell me, if this project will be maintained in the future? I really would like to use it but it looks a bit outdated. I would also propose some help if needed. Thank you very much in advance

**Comment by ValorVl** [comment]
Hi. Also interested this question.

**Comment by YunaBraska** [comment]
See issue: #36  There will be the next release soon. Even without new release, there are active commits :)
