### ISSUE TITLE
how to support nats cluster 

### ISSUE THREAD

**Issue by wangliguokaka** [nats-io/spring-nats#23]
for the nats cluster,how to config it? thank you

**Comment by scottf** [comment]
@wangliguokaka Here is a good place to start. https://docs.nats.io/running-a-nats-service/configuration/clustering/cluster_config

**Comment by wangliguokaka** [comment]
I want that how to config yml file to connect nats streaming.

I don't know where to config nats streaming's cluster id

**Comment by scottf** [comment]
@wangliguokaka Is there any way you can convert to JetStream? NatStreaming is end of life

**Comment by scottf** [comment]
One of our maintainers has some examples here: https://github.com/ColinSullivan1/js-experiments/tree/main/3node
