### ISSUE TITLE
Confusing naming for keystore type in connection properties

### ISSUE THREAD

**Issue by dschulz** [nats-io/spring-nats#25]
I think there's a confusion in some concepts which lead to incorrect naming in some connection properties.
Currently there are two properties that allow overriding the Key Manager's *provider algorithm*, not the keystore type, which is fixed to "JKS". I discovered this issue by trying to use a PKCS12 (.p12 file) keystore instead of JKS.

The Keystore Type is a different concept and possible values can be "JKS", "PKCS12", "JCEKS", "DKS", "BKS" , etc. 

```
nats.spring.key-store-type
nats.spring.trust-store-type

```
These two props default to "SunX509" which is the usual *provider algorithm* not a *keystore type*. Another well known provider algorithm is "PKIX".

In my opinion, the code in NatsConnectionProperties.java needs to be rearranged to correctly reflect these concepts and to allow using a different Keystore Type.

```
nats.spring.key-store-type=[ "JKS" | "PKCS12" | "JCEKS" | "DKS" | "BKS", "..."]
nats.spring.trust-store-type=[ "JKS" | "PKCS12" | "JCEKS" | "DKS" | "BKS", "..." ]
nats.spring.key-store-provider=["SunX509" | "PKIX"]
nats.spring.trust-store-provider=["SunX509" | "PKIX"]

```

Then the methods returning TrustManager[] and KeyManager[] should receive a string more aptly named "provider" or "providerAlgo" but not "type". 
The loadKeystore() method should be aware of a new "keyStoreType" property to instantiate KeyStore objects with the desired format.

**Comment by scottf** [comment]
Any chance you would want to make a PR to address this? This code base has not been touched except for administrative things in years.

**Comment by dschulz** [comment]
Hi @scottf. Thanks for the quick response. 
Yes, I'm willing to try and fix this issue 👍
