### ISSUE TITLE
Is this repository still alive?

### ISSUE THREAD

**Issue by PeterJakubik** [nats-io/spring-nats#36]
The last 0.5.6 release was May 25, 2022 and that's also in maven repository

**Comment by YunaBraska** [comment]
Hi @PeterJakubik yes this project is still alive. And you are right, it might be a good time to create the next release. 
@scottf do you think its possible to release the current state in the near future?

**Comment by scottf** [comment]
It's alive but that's about it. Not really any work going on here. I will do a release today.
