### ISSUE TITLE
0.6.0-3.1 version is not presented in the maven central

### ISSUE THREAD

**Issue by kruchkou** [nats-io/spring-nats#48]
Hello, dear maintainers! 

It seems like the latest version (0.6.0) for Spring Boot 3 is still not uploaded to the Maven central repo.
Could I ask you to take a look?

Many thanks for considering my request.

https://mvnrepository.com/artifact/io.nats/nats-spring-boot-starter
https://mvnrepository.com/artifact/io.nats/nats-spring

**Comment by scottf** [comment]
This has been deployed. It takes a day to be propagated to maven central
