### ISSUE TITLE
Invalid POM XMLs uploaded to Maven Central, Gradle build fails

### ISSUE THREAD

**Issue by CarloWakefield** [nats-io/spring-nats#5]
Both the version 0.3.0 and the version 0.3.1 have invalid POM XML uploaded to the Maven Central.

- https://repo.maven.apache.org/maven2/io/nats/spring-cloud-stream-binder-nats/0.3.1/spring-cloud-stream-binder-nats-0.3.1.pom
- https://repo.maven.apache.org/maven2/io/nats/spring-cloud-stream-binder-nats/0.3.0/spring-cloud-stream-binder-nats-0.3.0.pom

Both contain an empty line at the start of the document. The result is that Gradle can't parse the POMs and hence the build fails.
Please fix those errors. How can they go unnoticed in the beginning?

**Comment by sasbury** [comment]
Odd, Maven was about to build, run tests, deploy to a repo manager that validated and uploaded to maven central. I suspect maven is more liberal than Gradle in some way.

I will take a look.

**Comment by sasbury** [comment]
Running a deploy but it takes several hours for the maven central to pick it up.

**Comment by ColinSullivan1** [comment]
@CarloWakefield , thank you for reporting this and providing the suggestion for a fix, as @sasbury mentioned, gradle must be less forgiving.  This is a fairly new NATS project, and we appreciate the feedback.

**Comment by sasbury** [comment]
Leaving this open until reporter confirms the fix in 0.3.2

**Comment by sasbury** [comment]
For our future reference, apparently sonatypes' Validate Pom doesn't check this...

<img width="367" alt="pom" src="https://user-images.githubusercontent.com/3311569/62642984-bab16200-b8fb-11e9-9afb-003f15e01148.png">

**Comment by sasbury** [comment]
0.3.2 is out with the fix, sadly sonatype tricked me the first time, but now it is out.

**Comment by CarloWakefield** [comment]
https://repo.maven.apache.org/maven2/io/nats/spring-cloud-stream-binder-nats/0.3.2/spring-cloud-stream-binder-nats-0.3.2.pom works as expected now.
Thank you very much for your quick response and fix.
